baseURL = "https://mabvmex.github.io/mabvmex-blog/". // ATENCIÃ“N a modificaciones
languageCode = "en-us"
title = "BitÃ¡cora Nerd personal"
theme = "hugo-winston-theme"
relativeURLs = true
canonifyURLs = true

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
paginate = 3

[params]
  google_analytics_id = ""
  # Hey Explorer aquÃ­ pon tu twitter ðŸ‘‡
  twitter_handle = "@mabvmex"
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showPostsOnHomepage = false
  addFrame = true
  addDot = true
